# Generated by Django 4.0.6 on 2022-07-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='my_id',
        ),
    ]
