# Generated by Django 4.0.6 on 2022-07-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_item_my_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='child_id',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
